<order_priority>
    1-URGENT
    <order_count>93</order_count>
</order_priority>
<order_priority>
    2-HIGH
    <order_count>103</order_count>
</order_priority>
<order_priority>
    3-MEDIUM
    <order_count>109</order_count>
</order_priority>
<order_priority>
    4-NOT SPECIFIED
    <order_count>102</order_count>
</order_priority>
<order_priority>
    5-LOW
    <order_count>128</order_count>
</order_priority>
